model_name: "gpt-5-nano"
task: "sentiment_classification_3level"

labels:
  - NEGATIF
  - NETRAL
  - POSITIF

score_mapping:
  NEGATIF: -1
  NETRAL: 0
  POSITIF: 1

max_completion_tokens: 64
temperature: 1.0

text:
  max_chars: 2000

max_workers: 5
intermediate_save_every_n_calls: 500

rate_limit_retry_max_attempts: 5
rate_limit_initial_delay: 0.5

reasoning_effort: "minimal"

debug_print_first_n: 5